### ISSUE TITLE
URL.update_query() should share implementation with URL.with_query()

### ISSUE THREAD

**Issue by asvetlov** [aio-libs/yarl#87]
The only difference is using `MultiDict.update()` instead of `MultiDict.extend()`, parameters parsing should be the same.

**Comment by vomindoraan** [comment]
Agreed, currently `URL('test').with_query(a=1)` will work, whereas `URL('test').update_query(a=1)` will fail with: `TypeError: Argument should be str`.

**Comment by alxpy** [comment]
this issue can be closed

**Comment by asvetlov** [comment]
Fixed by #115

**Comment by vomindoraan** [comment]
I see this was merged into master in mid October, but apparently it still hasn't been put into a release, because we're still having the same problem we've been having for the past 5 months, and we updated to yarl 0.16.0.

When will this be released?

**Comment by vomindoraan** [comment]
Actually, it appears that both `update_query` _and_ `with_query` fail with ints now. So I guess that this _has_ been released, just that the inferior `update_query` implementation was shared with `with_query` instead of the other way around. I'll make a new issue for this.
